from utils import Generator, camelcase


def peer(gen: Generator, peer):
    gen.emit("#pragma once")  # u mad molly ?

    gen.emit("")
    gen.emit("// Don't edit this code !")
    gen.emit("// It was generated by ipc-compiler.py")
    gen.emit("")

    gen.emit(f"class {camelcase(peer['name'])}")
    gen.emit("{")
    gen.emit("};")
