#pragma once

typedef enum
{
    MOUSE_CURSOR_STATE_DEFAULT,
    MOUSE_CURSOR_STATE_DISABLED,
    MOUSE_CURSOR_STATE_BUSY,
    MOUSE_CURSOR_STATE_TEXT,
    MOUSE_CURSOR_STATE_MOVE,
    MOUSE_CURSOR_STATE_RESIZEH,
    MOUSE_CURSOR_STATE_RESIZEV,
    MOUSE_CURSOR_STATE_RESIZEHV,
    MOUSE_CURSOR_STATE_RESIZEVH,
    MOUSE_CURSOR_STATE_COUNT,
} mouse_cursor_state_t;

typedef struct
{

} widget_t;
