TAG(__UNKNOWN__, __unknown__)

// Graphical elements

TAG(CIRCLE, circle)
TAG(ELLIPSE, ellipse)
TAG(G, g)
TAG(LINE, line)
TAG(PATH, path)
TAG(POLYGON, polygon)
TAG(POLYLINE, polyline)
TAG(RECT, rect)
TAG(SVG, svg)
TAG(TEXT, text)
TAG(TEXT_PATH, textPath)
TAG(TSPAN, tspan)

// Other elements

TAG(CLIP_PATH, clipPath)
TAG(DEFS, defs)
TAG(DESC, desc)
TAG(FOREIGN_OBJECT, foreignObject)
TAG(LINEAR_GRADIENT, linearGradient)
TAG(MASK, mask)
TAG(RADIAL_GRADIENT, radialGradient)
TAG(SCRIPT, script)
TAG(STOP, stop)
TAG(STYLE, style)
TAG(SYMBOL, symbol)
TAG(TITLE, title)
TAG(USE, use)
