#pragma once

enum TerminalColor
{
    TERMINAL_COLOR_BLACK,
    TERMINAL_COLOR_RED,
    TERMINAL_COLOR_GREEN,
    TERMINAL_COLOR_YELLOW,
    TERMINAL_COLOR_BLUE,
    TERMINAL_COLOR_MAGENTA,
    TERMINAL_COLOR_CYAN,
    TERMINAL_COLOR_GREY,
    TERMINAL_COLOR_BRIGHT_BLACK,
    TERMINAL_COLOR_BRIGHT_RED,
    TERMINAL_COLOR_BRIGHT_GREEN,
    TERMINAL_COLOR_BRIGHT_YELLOW,
    TERMINAL_COLOR_BRIGHT_BLUE,
    TERMINAL_COLOR_BRIGHT_MAGENTA,
    TERMINAL_COLOR_BRIGHT_CYAN,
    TERMINAL_COLOR_BRIGHT_GREY,

    TERMINAL_COLOR_DEFAULT_FOREGROUND,
    TERMINAL_COLOR_DEFAULT_BACKGROUND,

    __TERMINAL_COLOR_COUNT
};
