#pragma once
// Generated by chatty from src/srvs/grund-echo/api.idl
// DO NOT EDIT
#include <karm-base/async.h>
namespace Grund::Echo {

struct IEcho {
    static constexpr auto _UID = 0xd31ef811301c6b41;
    static constexpr auto _NAME = "Echo";

    template <typename T>
    struct _Client;

    auto _dispatch(auto &);

    virtual ~IEcho() = default;

    static constexpr auto pingAsync_UID = 0x0b0a4b8aec6e280a;
    virtual Async::Task<String> pingAsync(String val) = 0;
};

template <typename T>
struct IEcho::_Client : public IEcho {
    T _t;

    _Client(T t) : _t{t} {}

    Async::Task<String> pingAsync(String val) {
        return _t.template invoke<IEcho, pingAsync_UID, Async::Task<String>, String>(val);
    }
};

auto IEcho::_dispatch(auto &o) {
    switch (o.mid) {

    case pingAsync_UID:
        return o.template call<String>([&]<typename... Args>(Args &&...args) {
            return pingAsync(std::forward<Args>(args)...);
        });

    default:
        return o.error();
    }
}

} // namespace Grund::Echo
