#pragma once

#include <libgraphic/Color.h>

#define THEME_DARK_BORDER RGBA(1, 1, 1, 0.12)
#define THEME_DARK_BACKGROUND COLOR(0x333333)
#define THEME_DARK_MIDDLEGROUND COLOR(0x444444)
#define THEME_DARK_FOREGROUND COLOR(0xFFFFFF)
#define THEME_DARK_FOREGROUND_INACTIVE COLOR(0x888888)
#define THEME_DARK_SELECTION ALPHA(COLOR(0x0066FF), 0.5)
#define THEME_DARK_SELECTION_INACTIVE ALPHA(COLOR(0x888888), 0.25)
#define THEME_DARK_ACCENT COLOR(0x0066FF)
#define THEME_DARK_ACCENT_INACTIVE COLOR(0x444444)

#define THEME_LIGHT_BORDER RGBA(0, 0, 0, 0.12)
#define THEME_LIGHT_BACKGROUND COLOR_WHITESMOKE
#define THEME_LIGHT_MIDDLEGROUND COLOR_WHITE
#define THEME_LIGHT_FOREGROUND COLOR_BLACK
#define THEME_LIGHT_FOREGROUND_INACTIVE COLOR_DIMGRAY
#define THEME_LIGHT_SELECTION ALPHA(COLOR(0x0066FF), 0.5)
#define THEME_LIGHT_SELECTION_INACTIVE ALPHA(COLOR(0x888888), 0.25)
#define THEME_LIGHT_ACCENT COLOR(0x0066FF)
#define THEME_LIGHT_ACCENT_INACTIVE COLOR_DIMGRAY

typedef enum
{
    THEME_BORDER,
    THEME_BACKGROUND,
    THEME_MIDDLEGROUND,
    THEME_FOREGROUND,
    THEME_FOREGROUND_DISABLED,
    THEME_SELECTED,
    THEME_ACCENT,

    __THEME_COLOR_COUNT
} ThemeColorRole;
