#pragma once

#include <libgraphic/Color.h>

#define THEME_DEFAULT_BORDER COLOR_RGBA(255, 255, 255, 31)
#define THEME_DEFAULT_BACKGROUND COLOR(0x333333)
#define THEME_DEFAULT_MIDDLEGROUND COLOR(0x444444)
#define THEME_DEFAULT_FOREGROUND COLOR(0xFFFFFF)
#define THEME_DEFAULT_FOREGROUND_INACTIVE COLOR(0x888888)
#define THEME_DEFAULT_FOREGROUND_DISABLED COLOR(0x888888)
#define THEME_DEFAULT_SELECTION COLOR_RGBA(0, 102, 255, 127)
#define THEME_DEFAULT_SELECTION_INACTIVE COLOR_RGBA(136, 136, 136, 63)
#define THEME_DEFAULT_ACCENT COLOR(0x0066FF)
#define THEME_DEFAULT_ACCENT_INACTIVE COLOR(0x444444)

#define THEME_DEFAULT_ANSI_CURSOR COLOR(0xffb454)
#define THEME_DEFAULT_ANSI_BACKGROUND COLOR(0x0a0e14)
#define THEME_DEFAULT_ANSI_FOREGROUND COLOR(0xb3b1ad)
#define THEME_DEFAULT_ANSI_BLACK COLOR(0x01060e)
#define THEME_DEFAULT_ANSI_RED COLOR(0xea6c73)
#define THEME_DEFAULT_ANSI_GREEN COLOR(0x91b362)
#define THEME_DEFAULT_ANSI_YELLOW COLOR(0xf9af4f)
#define THEME_DEFAULT_ANSI_BLUE COLOR(0x53bdfa)
#define THEME_DEFAULT_ANSI_MAGENTA COLOR(0xfae994)
#define THEME_DEFAULT_ANSI_CYAN COLOR(0x90e1c6)
#define THEME_DEFAULT_ANSI_WHITE COLOR(0xc7c7c7)
#define THEME_DEFAULT_ANSI_BRIGHT_BLACK COLOR(0x686868)
#define THEME_DEFAULT_ANSI_BRIGHT_RED COLOR(0xf07178)
#define THEME_DEFAULT_ANSI_BRIGHT_GREEN COLOR(0xc2d94c)
#define THEME_DEFAULT_ANSI_BRIGHT_YELLOW COLOR(0xffb454)
#define THEME_DEFAULT_ANSI_BRIGHT_BLUE COLOR(0x59c2ff)
#define THEME_DEFAULT_ANSI_BRIGHT_MAGENTA COLOR(0xffee99)
#define THEME_DEFAULT_ANSI_BRIGHT_CYAN COLOR(0x95e6cb)
#define THEME_DEFAULT_ANSI_BRIGHT_WHITE COLOR(0xffffff)

enum ThemeColorRole
{
    THEME_BORDER,
    THEME_BACKGROUND,
    THEME_MIDDLEGROUND,
    THEME_FOREGROUND,
    THEME_FOREGROUND_INACTIVE,
    THEME_FOREGROUND_DISABLED,
    THEME_SELECTION,
    THEME_SELECTION_INACTIVE,
    THEME_ACCENT,
    THEME_ACCENT_INACTIVE,

    THEME_ANSI_CURSOR,
    THEME_ANSI_BACKGROUND,
    THEME_ANSI_FOREGROUND,

    THEME_ANSI_BLACK,
    THEME_ANSI_RED,
    THEME_ANSI_GREEN,
    THEME_ANSI_YELLOW,
    THEME_ANSI_BLUE,
    THEME_ANSI_MAGENTA,
    THEME_ANSI_CYAN,
    THEME_ANSI_WHITE,

    THEME_ANSI_BRIGHT_BLACK,
    THEME_ANSI_BRIGHT_RED,
    THEME_ANSI_BRIGHT_GREEN,
    THEME_ANSI_BRIGHT_YELLOW,
    THEME_ANSI_BRIGHT_BLUE,
    THEME_ANSI_BRIGHT_MAGENTA,
    THEME_ANSI_BRIGHT_CYAN,
    THEME_ANSI_BRIGHT_WHITE,

    __THEME_COLOR_COUNT
};

bool theme_is_dark();

void theme_load(const char *path);

Color theme_get_color(ThemeColorRole role);
