#define COLOR_LIST(__ENTRY)                   \
    __ENTRY(TRANSPARENT, 0xFFFFFF00)          \
    __ENTRY(BLACKTRANSPARENT, 0x00000000)     \
    __ENTRY(WHITETRANSPARENT, 0xFFFFFF00)     \
    __ENTRY(ALICEBLUE, 0xF0F8FFFF)            \
    __ENTRY(ANTIQUEWHITE, 0xFAEBD7FF)         \
    __ENTRY(AQUA, 0x00FFFFFF)                 \
    __ENTRY(AQUAMARINE, 0x7FFFD4FF)           \
    __ENTRY(AZURE, 0xF0FFFFFF)                \
    __ENTRY(BEIGE, 0xF5F5DCFF)                \
    __ENTRY(BISQUE, 0xFFE4C4FF)               \
    __ENTRY(BLACK, 0x000000FF)                \
    __ENTRY(BLANCHEDALMOND, 0xFFEBCDFF)       \
    __ENTRY(BLUE, 0x0000FFFF)                 \
    __ENTRY(BLUEVIOLET, 0x8A2BE2FF)           \
    __ENTRY(BROWN, 0xA52A2AFF)                \
    __ENTRY(BURLYWOOD, 0xDEB887FF)            \
    __ENTRY(CADETBLUE, 0x5F9EA0FF)            \
    __ENTRY(CHARTREUSE, 0x7FFF00FF)           \
    __ENTRY(CHOCOLATE, 0xD2691EFF)            \
    __ENTRY(CORAL, 0xFF7F50FF)                \
    __ENTRY(CORNFLOWERBLUE, 0x6495EDFF)       \
    __ENTRY(CORNSILK, 0xFFF8DCFF)             \
    __ENTRY(CRIMSON, 0xDC143CFF)              \
    __ENTRY(CYAN, 0x00FFFFFF)                 \
    __ENTRY(DARKBLUE, 0x00008BFF)             \
    __ENTRY(DARKCYAN, 0x008B8BFF)             \
    __ENTRY(DARKGOLDENROD, 0xB8860BFF)        \
    __ENTRY(DARKGRAY, 0xA9A9A9FF)             \
    __ENTRY(DARKGREY, 0xA9A9A9FF)             \
    __ENTRY(DARKGREEN, 0x006400FF)            \
    __ENTRY(DARKKHAKI, 0xBDB76BFF)            \
    __ENTRY(DARKMAGENTA, 0x8B008BFF)          \
    __ENTRY(DARKOLIVEGREEN, 0x556B2FFF)       \
    __ENTRY(DARKORANGE, 0xFF8C00FF)           \
    __ENTRY(DARKORCHID, 0x9932CCFF)           \
    __ENTRY(DARKRED, 0x8B0000FF)              \
    __ENTRY(DARKSALMON, 0xE9967AFF)           \
    __ENTRY(DARKSEAGREEN, 0x8FBC8FFF)         \
    __ENTRY(DARKSLATEBLUE, 0x483D8BFF)        \
    __ENTRY(DARKSLATEGRAY, 0x2F4F4FFF)        \
    __ENTRY(DARKSLATEGREY, 0x2F4F4FFF)        \
    __ENTRY(DARKTURQUOISE, 0x00CED1FF)        \
    __ENTRY(DARKVIOLET, 0x9400D3FF)           \
    __ENTRY(DEEPPINK, 0xFF1493FF)             \
    __ENTRY(DEEPSKYBLUE, 0x00BFFFFF)          \
    __ENTRY(DIMGRAY, 0x696969FF)              \
    __ENTRY(DIMGREY, 0x696969FF)              \
    __ENTRY(DODGERBLUE, 0x1E90FFFF)           \
    __ENTRY(FIREBRICK, 0xB22222FF)            \
    __ENTRY(FLORALWHITE, 0xFFFAF0FF)          \
    __ENTRY(FORESTGREEN, 0x228B22FF)          \
    __ENTRY(FUCHSIA, 0xFF00FFFF)              \
    __ENTRY(GAINSBORO, 0xDCDCDCFF)            \
    __ENTRY(GHOSTWHITE, 0xF8F8FFFF)           \
    __ENTRY(GOLD, 0xFFD700FF)                 \
    __ENTRY(GOLDENROD, 0xDAA520FF)            \
    __ENTRY(GRAY, 0x808080FF)                 \
    __ENTRY(GREY, 0x808080FF)                 \
    __ENTRY(GREEN, 0x008000FF)                \
    __ENTRY(GREENYELLOW, 0xADFF2FFF)          \
    __ENTRY(HONEYDEW, 0xF0FFF0FF)             \
    __ENTRY(HOTPINK, 0xFF69B4FF)              \
    __ENTRY(INDIANRED, 0xCD5C5CFF)            \
    __ENTRY(INDIGO, 0x4B0082FF)               \
    __ENTRY(IVORY, 0xFFFFF0FF)                \
    __ENTRY(KHAKI, 0xF0E68CFF)                \
    __ENTRY(LAVENDER, 0xE6E6FAFF)             \
    __ENTRY(LAVENDERBLUSH, 0xFFF0F5FF)        \
    __ENTRY(LAWNGREEN, 0x7CFC00FF)            \
    __ENTRY(LEMONCHIFFON, 0xFFFACDFF)         \
    __ENTRY(LIGHTBLUE, 0xADD8E6FF)            \
    __ENTRY(LIGHTCORAL, 0xF08080FF)           \
    __ENTRY(LIGHTCYAN, 0xE0FFFFFF)            \
    __ENTRY(LIGHTGOLDENRODYELLOW, 0xFAFAD2FF) \
    __ENTRY(LIGHTGRAY, 0xD3D3D3FF)            \
    __ENTRY(LIGHTGREY, 0xD3D3D3FF)            \
    __ENTRY(LIGHTGREEN, 0x90EE90FF)           \
    __ENTRY(LIGHTPINK, 0xFFB6C1FF)            \
    __ENTRY(LIGHTSALMON, 0xFFA07AFF)          \
    __ENTRY(LIGHTSEAGREEN, 0x20B2AAFF)        \
    __ENTRY(LIGHTSKYBLUE, 0x87CEFAFF)         \
    __ENTRY(LIGHTSLATEGRAY, 0x778899FF)       \
    __ENTRY(LIGHTSLATEGREY, 0x778899FF)       \
    __ENTRY(LIGHTSTEELBLUE, 0xB0C4DEFF)       \
    __ENTRY(LIGHTYELLOW, 0xFFFFE0FF)          \
    __ENTRY(LIME, 0x00FF00FF)                 \
    __ENTRY(LIMEGREEN, 0x32CD32FF)            \
    __ENTRY(LINEN, 0xFAF0E6FF)                \
    __ENTRY(MAGENTA, 0xFF00FFFF)              \
    __ENTRY(MAROON, 0x800000FF)               \
    __ENTRY(MEDIUMAQUAMARINE, 0x66CDAAFF)     \
    __ENTRY(MEDIUMBLUE, 0x0000CDFF)           \
    __ENTRY(MEDIUMORCHID, 0xBA55D3FF)         \
    __ENTRY(MEDIUMPURPLE, 0x9370DBFF)         \
    __ENTRY(MEDIUMSEAGREEN, 0x3CB371FF)       \
    __ENTRY(MEDIUMSLATEBLUE, 0x7B68EEFF)      \
    __ENTRY(MEDIUMSPRINGGREEN, 0x00FA9AFF)    \
    __ENTRY(MEDIUMTURQUOISE, 0x48D1CCFF)      \
    __ENTRY(MEDIUMVIOLETRED, 0xC71585FF)      \
    __ENTRY(MIDNIGHTBLUE, 0x191970FF)         \
    __ENTRY(MINTCREAM, 0xF5FFFAFF)            \
    __ENTRY(MISTYROSE, 0xFFE4E1FF)            \
    __ENTRY(MOCCASIN, 0xFFE4B5FF)             \
    __ENTRY(NAVAJOWHITE, 0xFFDEADFF)          \
    __ENTRY(NAVY, 0x000080FF)                 \
    __ENTRY(OLDLACE, 0xFDF5E6FF)              \
    __ENTRY(OLIVE, 0x808000FF)                \
    __ENTRY(OLIVEDRAB, 0x6B8E23FF)            \
    __ENTRY(ORANGE, 0xFFA500FF)               \
    __ENTRY(ORANGERED, 0xFF4500FF)            \
    __ENTRY(ORCHID, 0xDA70D6FF)               \
    __ENTRY(PALEGOLDENROD, 0xEEE8AAFF)        \
    __ENTRY(PALEGREEN, 0x98FB98FF)            \
    __ENTRY(PALETURQUOISE, 0xAFEEEEFF)        \
    __ENTRY(PALEVIOLETRED, 0xDB7093FF)        \
    __ENTRY(PAPAYAWHIP, 0xFFEFD5FF)           \
    __ENTRY(PEACHPUFF, 0xFFDAB9FF)            \
    __ENTRY(PERU, 0xCD853FFF)                 \
    __ENTRY(PINK, 0xFFC0CBFF)                 \
    __ENTRY(PLUM, 0xDDA0DDFF)                 \
    __ENTRY(POWDERBLUE, 0xB0E0E6FF)           \
    __ENTRY(PURPLE, 0x800080FF)               \
    __ENTRY(REBECCAPURPLE, 0x663399FF)        \
    __ENTRY(RED, 0xFF0000FF)                  \
    __ENTRY(ROSYBROWN, 0xBC8F8FFF)            \
    __ENTRY(ROYALBLUE, 0x4169E1FF)            \
    __ENTRY(SADDLEBROWN, 0x8B4513FF)          \
    __ENTRY(SALMON, 0xFA8072FF)               \
    __ENTRY(SANDYBROWN, 0xF4A460FF)           \
    __ENTRY(SEAGREEN, 0x2E8B57FF)             \
    __ENTRY(SEASHELL, 0xFFF5EEFF)             \
    __ENTRY(SIENNA, 0xA0522DFF)               \
    __ENTRY(SILVER, 0xC0C0C0FF)               \
    __ENTRY(SKYBLUE, 0x87CEEBFF)              \
    __ENTRY(SLATEBLUE, 0x6A5ACDFF)            \
    __ENTRY(SLATEGRAY, 0x708090FF)            \
    __ENTRY(SLATEGREY, 0x708090FF)            \
    __ENTRY(SNOW, 0xFFFAFAFF)                 \
    __ENTRY(SPRINGGREEN, 0x00FF7FFF)          \
    __ENTRY(STEELBLUE, 0x4682B4FF)            \
    __ENTRY(TAN, 0xD2B48CFF)                  \
    __ENTRY(TEAL, 0x008080FF)                 \
    __ENTRY(THISTLE, 0xD8BFD8FF)              \
    __ENTRY(TOMATO, 0xFF6347FF)               \
    __ENTRY(TURQUOISE, 0x40E0D0FF)            \
    __ENTRY(VIOLET, 0xEE82EEFF)               \
    __ENTRY(WHEAT, 0xF5DEB3FF)                \
    __ENTRY(WHITE, 0xFFFFFFFF)                \
    __ENTRY(WHITESMOKE, 0xF5F5F5FF)           \
    __ENTRY(YELLOW, 0xFFFF00FF)               \
    __ENTRY(YELLOWGREEN, 0x9ACD32FF)
