name: Checks (Ubuntu)

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.11'

      - name: Set up the build environment
        run: ./skift.sh tools setup && ./skift.sh tools doctor

      - name: Download third-party dependencies
        run: ./skift.sh model install

      - name: Build Kernel (x86_64)
        run: ./skift.sh build --target=kernel-x86_64

      - name: Build EFI (x86_64)
        run: ./skift.sh build --target=efi-x86_64

      - name: Build Userspace (x86_64)
        run: ./skift.sh build --target=skift-x86_64

      - name: Build Userspace (Host)
        run: ./skift.sh build

      - name: Test Userspace (Host)
        run: ./skift.sh test

      - name: Check for formatting errors
        run: ./meta/scripts/style-check.sh || echo "Please run ./meta/scripts/style-format.sh"
